name = "doh-cache"
type = "javascript"

workers_dev = false
account_id = ""
zone_id = "7164b7afd9967d0ac5e29f1321cf3031"
routes = ["https://dns.paesa.es/dns-query", "https://doh.paesa.es/dns-query"]

compatibility_date = "2021-10-26"
